config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/homeVeterinario' => "veterinarios#homeVeterinario"
  get '/homeClientes' => "clientes#homeClientes"

  # get '/registrarCliente', to: 'personas#new_user_and_persona'
  get '/registrarCliente', to: 'personas#new_user_and_persona', as: 'new_user_and_persona'
  post '/registrarCliente', to: 'personas#create_user_and_persona'

  get '/mi_perfil/:id', to: 'personas#show_mydata', as: 'show_my_data'

  get '/personas/:persona_id/perros/personaperro', to: 'perros#personaperro', as: 'persona_perros_personaperro'
  get '/personas/:id/datos_personales', to: 'personas#datos_personales', as: 'persona_datos_personales'

  get '/index/:id/ver_info_perro', to: 'perros#ver_info_perro', as: 'ver_info_perro'

  get '/turnos_del_dia', to: 'turnos#turnos_del_dia', as: 'turnos_del_dia'

  get 'turnos/:id/aceptar', to: 'turnos#aceptar', as: 'aceptar_turno'
  post 'procesar_aceptar/:id', to: 'turnos#procesar_aceptar', as: 'procesar_aceptar_turno'
  get 'turnos/:id/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'procesar_rechazar/:id', to: 'turnos#procesar_rechazar', as: 'procesar_rechazar_turno'

  post 'perroEncontrado/:id', to: 'perdido_encontrados#marcar_encontrado', as: 'marcar_encontrado'

  get 'turnos_del_dia/:id', to: 'turnos#ausente', as: 'ausente_turno'
  get 'turnos_del_dia/:id/presente', to: 'turnos#presente', as: 'presente_turno'
  # resources :tipo_turnos
  get '/index/:id/ver_info_perro/historia_clinica', to: 'perros#historia_clinica', as: 'historia_clinica_perro'
  get '/index/:id/ver_info_perro/libreta_sanitaria', to: 'perros#libreta_sanitaria', as: 'libreta_sanitaria_perro'

  get '/personas/:id/editar', to: 'personas#editar', as: 'personas_editar'
  patch '/personas/:id/editar', to: 'personas#update', as: 'actualizar_mi_perfil'

  get '/turnos/subirUrgencia', to: 'turnos#newUrgencia', as: 'new_urgencia'
  post '/turnos/subirUrgencia', to: 'turnos#createUrgencia'

  get '/turnosAll', to: 'turnos#mostrarTodos', as: 'turnos_todos'

  get '/nueva_campania', to: 'campania_donacions#new', as: 'nueva_campania'
  post '/crear_campania', to: 'campania_donacions#create', as: 'crear_campania'

  get '/vista_veterinario', to: 'campania_donacions#vistaVeterinario', as: 'vista_veterinario'

  get '/editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'

  get '/ver_campanias', to: 'campania_donacions#vistaUsuario', as: 'ver_campanias'

  get '/ver_campanias_publico', to: 'campania_donacions#vistaPublica', as: 'ver_campanias_publico'

  get '/ver_campanias/:id/donar', to: 'tarjeta_creditos#donar', as: 'donar'
  get '/ver_campanias/:id/donarVisitante', to: 'tarjeta_creditos#donarVisitante', as: 'donar_visitante'
  # post 'campanias/:id/procesar_donacion', to: 'campanias#procesar_donacion', as: 'procesar_donacion_campania'
  post '/procesar_dono', to: 'tarjeta_creditos#procesar_dono', as: 'procesar_dono'
  post '/procesar_visitante', to: 'tarjeta_creditos#procesar_dono_visitante', as: 'procesar_dono_visitante'

  get '/historial_gastos', to: 'turnos#historial_gastos', as: 'historial_gastos'

  get '/get_perros_by_persona', to: 'turnos#get_perros_by_persona'

  get '/ver_paseadores_publico', to: 'paseadors#index_paseador_guest', as: 'index_paseador_guest'

  get '/ver_paseadores', to: 'paseadors#index_paseador_usuario', as: 'index_paseador_usuario'

  get '/ver_paseadores_veterinario', to: 'paseadors#index_paseador_veterinario', as:'index_paseador_veterinario'

  # get '/nuevo_paseador', to: 'paseadors#new', as: 'nuevo_paseador'
  # post '/crear_paseador', to: 'paseadors#create', as: 'crear_paseador'

  get '/newPaseador', to: 'paseadors#newPaseador', as: 'new_paseador'
  post '/create_paseador', to: 'paseadors#createPaseador', as: 'create_paseador'
  get '/newCuidador', to: 'paseadors#newCuidador', as: 'new_cuidador'
  post '/create_cuidador', to: 'paseadors#createCuidador', as: 'create_cuidador'

  get '/perdido_encontrado_nuevo', to: 'perdido_encontrados#new', as: 'nuevo_perdido_encontrado'
  post '/crear_perdido_encontrado', to: 'perdido_encontrados#create', as: 'crear_perdido_encontrado'

  get '/encontrado_nuevo', to: 'encontrados#new', as: 'nuevo_encontrado'
  post '/crear_encontrado', to: 'encontrados#create', as: 'crear_encontrado'
  resources :encontrados

  get '/perdido_encontrado_usuario', to: 'perdido_encontrados#perdido_encontrado_usuario', as:'perdido_encontrado_usuario'

  get '/encontrado_usuario', to: 'encontrados#index_encontrado_usuario', as:'index_encontrado_usuario'

  get '/perdido_encontrado_visitante', to: 'perdido_encontrados#perdido_encontrado_visitante', as: 'perdido_encontrado_visitante'

  get '/perdido_mis_publicaciones', to: 'perdido_encontrados#mis_publicaciones_perdidos', as: 'mis_publicaciones_perdidos'

  get '/mis_publicaciones_encontrados', to: 'encontrados#mis_publicaciones_encontrados', as: 'mis_publicaciones_encontrados'

  get '/vista_visitantes_encontrados', to: 'encontrados#index_encontrado_visitante', as: 'index_encontrado_visitante'

  get '/paseadores/:id/editar', to: 'paseadors#edit', as: 'paseadors_editar'
  patch '/paseadores/:id/editar', to: 'paseadors#update', as: 'actualizar_paseadors'

  get '/perdidos/reencuentros', to: 'perdido_encontrados#show_reencuentros', as: 'perros_perdidos_y_encontrados'

  # patch '/mi_perfil/:id/actualizar', to: 'personas#update', as: 'actualizar_mi_perfil'

  resources :campania_donacions, only:[:new, :create, :vistaVeterinario, :editar, :update, :vistaUsuario]

  resources :perdido_encontrados, only:[:new, :create, :perdido_encontrado_usuario, :perdido_encontrado_visitante, :mis_publicaciones_perdidos]

  resources :encontrados, only:[:new, :create, :index_encontrado_usuario, :mis_publicaciones_encontrados, :index_encontrado_visitante]

  resources :paseadors, only:[:new, :create, :index_paseador_guest, :index_paseador_usuario, :index_paseador_veterinario, :edit, :update]

  resources :tarjeta_creditos, only:[:new, :index, :create, :edit, :update, :destroy, :informacion_correcta, :donar]

  resources :perros, only: [:new, :create, :index, :personaperro, :ver_info_perro]

  resources :turnos, only: [:new, :create, :show, :index, :turnos_del_dia, :update, :historial_gastos, :get_perros_by_persona]

  resources :personas, only: [:new, :create, :index, :editar, :update]

  resources :personas, only: [:new, :create, :index, :edit, :update] do
    resources :perros, only: [:personaperro, :new, :create]  # Agrega ruta anidada solo para la acción index de perros
  end

  post '/personas/:id/baja', to: 'veterinarios#baja_logica_cliente', as: 'baja_persona'
  post '/perros/:id/baja', to: 'personas#baja_logica_perro', as: 'baja_perro'

  get '/under_construction', to: 'application#under_construction'

  get '/turnos/:id/historiaClinica', to: 'turnos#show_turno_historiaClinica', as: 'show_turno_historia'
  get '/turnos/:id/libretaSanitaria', to: 'turnos#show_turno_libretaSanitaria', as: 'show_turno_libreta'

  get '/adopciones', to: 'adopcions#index', as: 'adopciones_index'
  # get '/home/adopciones', to: 'adopcions#adopcionesVisitante', as: 'adopciones_index_visitante'

  get '/adopciones/publicar/:id', to: 'adopcions#new', as: 'adopciones_publicacion_new'
  post 'adopciones/publicar', to: 'adopcions#create', as: 'adopciones_post_publicacion_new'
  get '/adopciones/:id/publicaciones', to: 'adopcions#mis_publicaciones', as: 'adopciones_mis_publicaciones'

  get '/adopciones/publicar_mi_perro/:id', to: 'adopcions#new_mi_perro', as: 'adopciones_publicacion_new_mi_perro'
  post 'adopciones/publicar_mi_perro', to: 'adopcions#create_mi_perro', as: 'adopciones_post_publicacion_new_mi_perro'
  resources :adopcions  # Add this line

  get '/adopciones/:id/contactar', to: 'adopcions#adoptar', as: 'mail_adopcion'
  post '/adopciones/:id/contactar', to: 'adopcions#adoptar_datos'

  post '/adopciones/:id/adoptado', to: 'adopcions#marcar_adoptado', as: 'marcar_adoptado'
  post '/encontrados/:id/recuperado', to: 'encontrados#marcar_recuperado', as: 'marcar_recuperado'

  #root to: 'application#home'
  root 'application#determine_root'

  # match "*path", to: "application#under_construction", via: :all
end

app/models/encontrado.rb
class Encontrado < ApplicationRecord
  belongs_to :user
  enum tamanio: { Chico: 1, Mediano: 2, Grande: 3}
  enum estado: {Encontrado: 0, Hallado: 1}

  validate :dia_no_futuro
  validates :lugar, presence: true
  validates :color, presence: true
  validates :tamanio, presence: true
  validates :dia, presence: true
  validates :descripcion, presence: true
  validates :estado, presence: true, inclusion: { in: estados.keys }

  private

  def dia_no_futuro
    if dia.present? && dia > Date.current
      errors.add(:dia, "no puede ser en el futuro")
    end
  end
end

app/controllers/encontrados_controller.rb
class EncontradosController < ApplicationController

  before_action :authenticate_user!, except: [:index_encontrado_visitante]  #Esto me muestra el cartel que luego hay que poner lindo
  before_action :authorize_client, only: [:new, :create, :index_encontrado_usuario, :mis_publicaciones_encontrados]
  #before_action :authorize_client, only: [:new, :create]
  layout 'clientes', only: [:new, :create, :index_encontrado_usuario, :mis_publicaciones_encontrados]

  def authorize_client
    unless current_user && current_user.role == "cliente"
      redirect_to root_path, alert: "No tenés permiso para acceder a esta página."
    end
  end

  def new
    @encontrado = Encontrado.new
  end

  def create
    @encontrado = Encontrado.new(encontrado_params)
    @encontrado.estado = 0
    if @encontrado.save
      redirect_to root_path, notice: 'Perro encontrado publicado correctamente.'
    else
      render :new
    end
  end

  def marcar_recuperado
    @publicacion = Encontrado.find(params[:id])
    if @publicacion.update_columns(estado: 'Hallado')
      redirect_to root_path, notice: 'El perro fue marcado como reencontrado!'
    else
      redirect_to root_path, alert: 'Error al marcar como reencontrado el perro.'
    end
  end

  def index_encontrado_usuario
    @encontrados = Encontrado.order(:estado)
    render(:layout => "layouts/clientes")
  end

  def index_encontrado_visitante
    @encontrados = Encontrado.order(:estado)
    render(:layout => "layouts/base")
  end

  def mis_publicaciones_encontrados
    @publicaciones = current_user.encontrados
    render(:layout => "layouts/clientes")
  end

  private

  def encontrado_params
    params.require(:encontrado).permit(:lugar, :dia, :descripcion, :color, :tamanio, :user_id)
  end
end

app/views/encontrados/index_encontrado_usuario.html.erb
<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 60px;">
    <i class="material-icons medium left grey" style="margin-right: 10px;">map</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Perros Encontrados</h2>
  </div>

  <div class="row">
    <div class="col-md-12 d-flex">
      <a class="btn btn-primary anchor-new-celeste" href="<%= nuevo_encontrado_path %>"
        style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:30%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center; margin-top: 5%; margin-top:10%; margin-right:3%;">
        Agregar
        <i class="material-icons" style="margin-left: 15px;">add</i>
      </a>
      <% if current_user %>
        <a class="btn btn-primary anchor-new-celeste" href="<%= mis_publicaciones_encontrados_path(id: current_user.persona.id) %>"
          style="background-color: rgb(252, 145, 14); border: none; border-radius: 2px; width: 30%; letter-spacing: 0.5px; vertical-align: center; display: flex; align-items: center; justify-content: center; margin-top:10%;">
          Mis publicaciones
          <i class="material-icons" style="margin-left: 15px;">visibility</i>
        </a>
      <% end %>
      <%# <a class="btn btn-primary anchor-new-celeste" href="<%= perros_perdidos_y_encontrados_path %>
        <%# style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:30%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center; margin-top: 5%; margin-top:10%; margin-right:3%;"> %>
        <%# Ver Reencuentros %>
      <%# </a> %> 
    </div>
  </div>
<% end %>

<% content_for :body do %>

  <% if @encontrados.any? %>
    <div class="col-md-12 mx-auto">
      <div class="card" style="border-radius:0;">
        <div class="card-content">
          <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
            <thead>
              <tr>
                <th>Lugar</th>
                <th>Dia</th>
                <th>Descripcio</th>
                <th>Color</th>
                <th>Tamanio</th>
                <th>Estado</th>
                <th>Contacto</th>
              </tr>
            </thead>
            <tbody>
              <% @encontrados.each do |encontrado| %>
                <% if encontrado.estado == 'Hallado' %>
                 <tr>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.lugar %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.dia %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.descripcion %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.color %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.tamanio %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.estado %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"> - </td>
                  </tr>
                <% else %>
                <tr class="item-perdido-encontrado">
                  <td><%= encontrado.lugar %></td>
                  <td><%= encontrado.dia %></td>
                  <td><%= encontrado.descripcion %></td>
                  <td><%= encontrado.color %></td>
                  <td><%= encontrado.tamanio %></td>
                  <td><%= encontrado.estado %></td>
                  <td><%= encontrado.user.email %></td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% else %>
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="card" style="border-radius: 0; position: relative; min-height: 100px;">
            <div class="card-content" style="position: relative; margin-bottom: 0;">
              <h4 class="mt-3">No hay registros de perros encontrados</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>


    <a class="btn btn-primary btn-volver" href="/"
    style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>

<% end %>

app/views/encontrados/index_encontrado_visitante.html.erb
<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 50px;">
    <i class="material-icons medium left grey" style="margin-right: 10px;">search</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Perros Encontrados</h2>
</div>
<% end %>

<% content_for :body do %>

  <div class="col-md-10 mx-auto">
    <div class="card" style="border-radius:0;">
      <div class="card-content">

    <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
      <thead>
        <tr>
          <th>Lugar</th>
          <th>Dia</th>
          <th>Descripción</th>
          <th>Color</th>
          <th>Tamaño</th>
          <th>Estado</th>
          <th>Contacto</th>
        </tr>
      </thead>
      <tbody>
        <% @encontrados.each do |encontrado| %>
          <% if encontrado.estado == 'Hallado' %>
            <tr>
            <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.lugar %></td>
            <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.dia %></td>
            <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.descripcion %></td>
            <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.color %></td>
            <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.tamanio %></td>
            <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.estado %></td>
            <td style="background-color: rgba(200, 247, 197);, 1"> - </td>
            </tr>
          <% else %>
            <tr class="item-perdido-encontrado">
              <td><%= encontrado.lugar %></td>
              <td><%= encontrado.dia %></td>
              <td><%= encontrado.descripcion %></td>
              <td><%= encontrado.color %></td>
              <td><%= encontrado.tamanio %></td>
              <td><%= encontrado.estado %></td>
              <td><%= encontrado.user.email %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>
    </div>

  <a class="btn btn-primary btn-volver" href="/"
    style="margin-left:7%;background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>



<% end %>

app/views/encontrados/mis_publicaciones_encontrados.html.erb
<% content_for :titulo do %>
  <br><br><br>
  <div style="display: flex; align-items: center; text-align: center;">
    <i class="material-icons small left grey" style="margin-right: 10px;">pets</i>
    <h2 style="margin-top: 4px; font-weight: 200; margin-bottom: 0;">&nbsp; Mis publicaciones de Encontrados</h2>
  </div>
<% end %> 

<% content_for :body do %>

  <% if @publicaciones && @publicaciones.any? %>
    <div class="card" style="border-radius:0;">
      <div class="card-content">
        <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
          <thead>
            <tr>
              <th scope="col">Estado</th>
              <th scope="col">Lugar</th>
              <th scope="col">Día</th>
              <th scope="col">Descripción</th>
              <th scope="col">Color</th>
              <th scope="col">Tamaño</th>
              <th> Acciones </th>
            </tr>
          </thead>
          <tbody>
            <% @publicaciones.each do |encontrado| %>
              <% if encontrado.estado == 'Hallado' %>
                 <tr>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.estado %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.lugar %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.dia %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.descripcion %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.color %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= encontrado.tamanio %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"> - </td>
                </tr>
              <% else %>
                <tr>
                  <td><%= encontrado.estado %></td>
                  <td><%= encontrado.lugar %></td>
                  <td><%= encontrado.dia %></td>
                  <td><%= encontrado.descripcion %></td>
                  <td><%= encontrado.color %></td>
                  <td><%= encontrado.tamanio %></td>
                  <td>
                    <% if user_signed_in? && current_user.id == encontrado.user_id && encontrado.estado == 'Encontrado' %>
                      <%= form_with(url: marcar_recuperado_path(encontrado.id), method: :post, class: 'confirm-form') do |form| %>
                        <button type="submit" class="btn-link" style="background:none; border:none; color: green;" data-bs-toggle="tooltip" data-bs-placement="top" title="Marcar como recuperado">
                          <i class="material-icons">check</i>
                        </button>
                      <% end %>
                    <% else %>
                      -
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="card" style="border-radius: 0; position: relative; min-height: 100px;">
            <div class="card-content" style="position: relative; margin-bottom: 0;">
              <h4 class="mt-3">No hay registros de animales encontrados</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <br>
  <a class="btn btn-primary btn-volver" href="/encontrado_usuario"
    style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>

   <script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    });
  </script>
<% end %>

app/views/encontrados/new.html.erb
<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 50px;">
    <i class="material-icons medium left grey" style="margin-right: 10px;">campaign</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Encontrado</h2>
</div>
<% end %>

<% content_for :body do %>

  <div class="container">
    <div class="row justify-content-left">
      <div class="col-md-7">
        <div class="card" style="border-radius:0; margin-left:10%;">
          <div class="card-content">
            <%= form_with(model: @encontrado, local: true) do |form| %>
              <% if @encontrado.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@encontrado.errors.count, "error") %> prohibieron que este encontrado sea guardado:</h2>

                  <ul>
                    <% @encontrado.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="d-flex">
                <div class="field" style="margin-left:20%; margin-top:4%;" >
                  <%= form.text_field :lugar, class: "form-control", placeholder: "Zona en la que se encontró", style: "width:120%;", required: true %>
                </div>
              </div>

              <div class="d-flex">
                <div class="field" style="margin-left:20%; margin-top:4%;" >
                  <%= form.date_field :dia, required: true, style: 'width:170%;' %>
                </div>
              </div>

              <div class="d-flex">
                <div class="field" style="margin-left:20%; margin-top:4%;" >
                  <%= form.text_area :descripcion, class: "form-control", placeholder: "Alguna descripción que facilite el hallazgo del perro", style: "width:120%;", required: true %>
                </div>
              </div>

              <div class="d-flex">
                <div class="field" style="margin-left:20%; margin-top:4%;" >
                  <%= form.text_field :color, class: "form-control", placeholder: "Color del perro", style: "width:120%;", required: true %>
                </div>
              </div>

              <div class="d-flex">
                <div class="field" style="margin-left:20%; margin-top:4%;" >
                  <%= form.collection_select(:tamanio, Encontrado.tamanios.keys, :to_s, :humanize, prompt: "Tamaño", style: "width:220%;", required: true) %>
                </div>
              </div>

              <%= form.hidden_field :estado, value: 1 %>
              <%= form.hidden_field :user_id, value: current_user.id %>

              <div class="d-flex justify-content-center align-items-center" style="min-height: 100px;">
                <div class="actions">
                  <%= form.submit "Publicar perro"  , class: 'btn btn-primary', style: 'background-color: rgb(252, 145, 14); border: none; border-radius: 2px; width: 200px; height: 35px; letter-spacing: 0.5px; color: white;'%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

   <a class="btn btn-primary btn-volver" href="/encontrado_usuario"
    style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>
<%# <%= link_to 'Volver', perdido_encontrado_usuario_path, class: 'btn btn-secondary' %>

<% end %>