config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/homeVeterinario' => "veterinarios#homeVeterinario"
  get '/homeClientes' => "clientes#homeClientes"

  # get '/registrarCliente', to: 'personas#new_user_and_persona'
  get '/registrarCliente', to: 'personas#new_user_and_persona', as: 'new_user_and_persona'
  post '/registrarCliente', to: 'personas#create_user_and_persona'

  get '/mi_perfil/:id', to: 'personas#show_mydata', as: 'show_my_data'

  get '/personas/:persona_id/perros/personaperro', to: 'perros#personaperro', as: 'persona_perros_personaperro'
  get '/personas/:id/datos_personales', to: 'personas#datos_personales', as: 'persona_datos_personales'

  get '/index/:id/ver_info_perro', to: 'perros#ver_info_perro', as: 'ver_info_perro'

  get '/turnos_del_dia', to: 'turnos#turnos_del_dia', as: 'turnos_del_dia'

  get 'turnos/:id/aceptar', to: 'turnos#aceptar', as: 'aceptar_turno'
  post 'procesar_aceptar/:id', to: 'turnos#procesar_aceptar', as: 'procesar_aceptar_turno'
  get 'turnos/:id/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'procesar_rechazar/:id', to: 'turnos#procesar_rechazar', as: 'procesar_rechazar_turno'

  post 'perroEncontrado/:id', to: 'perdido_encontrados#marcar_encontrado', as: 'marcar_encontrado'

  get 'turnos_del_dia/:id', to: 'turnos#ausente', as: 'ausente_turno'
  get 'turnos_del_dia/:id/presente', to: 'turnos#presente', as: 'presente_turno'
  # resources :tipo_turnos
  get '/index/:id/ver_info_perro/historia_clinica', to: 'perros#historia_clinica', as: 'historia_clinica_perro'
  get '/index/:id/ver_info_perro/libreta_sanitaria', to: 'perros#libreta_sanitaria', as: 'libreta_sanitaria_perro'

  get '/personas/:id/editar', to: 'personas#editar', as: 'personas_editar'
  patch '/personas/:id/editar', to: 'personas#update', as: 'actualizar_mi_perfil'

  get '/turnos/subirUrgencia', to: 'turnos#newUrgencia', as: 'new_urgencia'
  post '/turnos/subirUrgencia', to: 'turnos#createUrgencia'

  get '/turnosAll', to: 'turnos#mostrarTodos', as: 'turnos_todos'

  get '/nueva_campania', to: 'campania_donacions#new', as: 'nueva_campania'
  post '/crear_campania', to: 'campania_donacions#create', as: 'crear_campania'

  get '/vista_veterinario', to: 'campania_donacions#vistaVeterinario', as: 'vista_veterinario'

  get '/editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'

  get '/ver_campanias', to: 'campania_donacions#vistaUsuario', as: 'ver_campanias'

  get '/ver_campanias_publico', to: 'campania_donacions#vistaPublica', as: 'ver_campanias_publico'

  get '/ver_campanias/:id/donar', to: 'tarjeta_creditos#donar', as: 'donar'
  get '/ver_campanias/:id/donarVisitante', to: 'tarjeta_creditos#donarVisitante', as: 'donar_visitante'
  # post 'campanias/:id/procesar_donacion', to: 'campanias#procesar_donacion', as: 'procesar_donacion_campania'
  post '/procesar_dono', to: 'tarjeta_creditos#procesar_dono', as: 'procesar_dono'
  post '/procesar_visitante', to: 'tarjeta_creditos#procesar_dono_visitante', as: 'procesar_dono_visitante'

  get '/historial_gastos', to: 'turnos#historial_gastos', as: 'historial_gastos'

  get '/get_perros_by_persona', to: 'turnos#get_perros_by_persona'

  get '/ver_paseadores_publico', to: 'paseadors#index_paseador_guest', as: 'index_paseador_guest'

  get '/ver_paseadores', to: 'paseadors#index_paseador_usuario', as: 'index_paseador_usuario'

  get '/ver_paseadores_veterinario', to: 'paseadors#index_paseador_veterinario', as:'index_paseador_veterinario'

  # get '/nuevo_paseador', to: 'paseadors#new', as: 'nuevo_paseador'
  # post '/crear_paseador', to: 'paseadors#create', as: 'crear_paseador'

  get '/newPaseador', to: 'paseadors#newPaseador', as: 'new_paseador'
  post '/create_paseador', to: 'paseadors#createPaseador', as: 'create_paseador'
  get '/newCuidador', to: 'paseadors#newCuidador', as: 'new_cuidador'
  post '/create_cuidador', to: 'paseadors#createCuidador', as: 'create_cuidador'

  get '/perdido_encontrado_nuevo', to: 'perdido_encontrados#new', as: 'nuevo_perdido_encontrado'
  post '/crear_perdido_encontrado', to: 'perdido_encontrados#create', as: 'crear_perdido_encontrado'

  get '/encontrado_nuevo', to: 'encontrados#new', as: 'nuevo_encontrado'
  post '/crear_encontrado', to: 'encontrados#create', as: 'crear_encontrado'
  resources :encontrados

  get '/perdido_encontrado_usuario', to: 'perdido_encontrados#perdido_encontrado_usuario', as:'perdido_encontrado_usuario'

  get '/encontrado_usuario', to: 'encontrados#index_encontrado_usuario', as:'index_encontrado_usuario'

  get '/perdido_encontrado_visitante', to: 'perdido_encontrados#perdido_encontrado_visitante', as: 'perdido_encontrado_visitante'

  get '/perdido_mis_publicaciones', to: 'perdido_encontrados#mis_publicaciones_perdidos', as: 'mis_publicaciones_perdidos'

  get '/mis_publicaciones_encontrados', to: 'encontrados#mis_publicaciones_encontrados', as: 'mis_publicaciones_encontrados'

  get '/vista_visitantes_encontrados', to: 'encontrados#index_encontrado_visitante', as: 'index_encontrado_visitante'

  get '/paseadores/:id/editar', to: 'paseadors#edit', as: 'paseadors_editar'
  patch '/paseadores/:id/editar', to: 'paseadors#update', as: 'actualizar_paseadors'

  get '/perdidos/reencuentros', to: 'perdido_encontrados#show_reencuentros', as: 'perros_perdidos_y_encontrados'

  # patch '/mi_perfil/:id/actualizar', to: 'personas#update', as: 'actualizar_mi_perfil'

  resources :campania_donacions, only:[:new, :create, :vistaVeterinario, :editar, :update, :vistaUsuario]

  resources :perdido_encontrados, only:[:new, :create, :perdido_encontrado_usuario, :perdido_encontrado_visitante, :mis_publicaciones_perdidos]

  resources :encontrados, only:[:new, :create, :index_encontrado_usuario, :mis_publicaciones_encontrados, :index_encontrado_visitante]

  resources :paseadors, only:[:new, :create, :index_paseador_guest, :index_paseador_usuario, :index_paseador_veterinario, :edit, :update]

  resources :tarjeta_creditos, only:[:new, :index, :create, :edit, :update, :destroy, :informacion_correcta, :donar]

  resources :perros, only: [:new, :create, :index, :personaperro, :ver_info_perro]

  resources :turnos, only: [:new, :create, :show, :index, :turnos_del_dia, :update, :historial_gastos, :get_perros_by_persona]

  resources :personas, only: [:new, :create, :index, :editar, :update]

  resources :personas, only: [:new, :create, :index, :edit, :update] do
    resources :perros, only: [:personaperro, :new, :create]  # Agrega ruta anidada solo para la acción index de perros
  end

  post '/personas/:id/baja', to: 'veterinarios#baja_logica_cliente', as: 'baja_persona'
  post '/perros/:id/baja', to: 'personas#baja_logica_perro', as: 'baja_perro'

  get '/under_construction', to: 'application#under_construction'

  get '/turnos/:id/historiaClinica', to: 'turnos#show_turno_historiaClinica', as: 'show_turno_historia'
  get '/turnos/:id/libretaSanitaria', to: 'turnos#show_turno_libretaSanitaria', as: 'show_turno_libreta'

  get '/adopciones', to: 'adopcions#index', as: 'adopciones_index'
  # get '/home/adopciones', to: 'adopcions#adopcionesVisitante', as: 'adopciones_index_visitante'

  get '/adopciones/publicar/:id', to: 'adopcions#new', as: 'adopciones_publicacion_new'
  post 'adopciones/publicar', to: 'adopcions#create', as: 'adopciones_post_publicacion_new'
  get '/adopciones/:id/publicaciones', to: 'adopcions#mis_publicaciones', as: 'adopciones_mis_publicaciones'

  get '/adopciones/publicar_mi_perro/:id', to: 'adopcions#new_mi_perro', as: 'adopciones_publicacion_new_mi_perro'
  post 'adopciones/publicar_mi_perro', to: 'adopcions#create_mi_perro', as: 'adopciones_post_publicacion_new_mi_perro'
  resources :adopcions  # Add this line

  get '/adopciones/:id/contactar', to: 'adopcions#adoptar', as: 'mail_adopcion'
  post '/adopciones/:id/contactar', to: 'adopcions#adoptar_datos'

  post '/adopciones/:id/adoptado', to: 'adopcions#marcar_adoptado', as: 'marcar_adoptado'
  post '/encontrados/:id/recuperado', to: 'encontrados#marcar_recuperado', as: 'marcar_recuperado'

  #root to: 'application#home'
  root 'application#determine_root'

  # match "*path", to: "application#under_construction", via: :all
end

app/models/adopcion.rb
class Adopcion < ApplicationRecord
    belongs_to :persona
    belongs_to :tipo_raza
    enum sexo: { Hembra: 0, Macho: 1 }
    enum tamanio: { Chico: 0, Mediano: 1, Grande: 2}
    enum estado: { Publicado: 0, Adoptado: 1 }

    validates :tipo_raza, :sexo, :tamanio, :origen, presence: {message: "Complete este campo por favor."}
end

app/controllers/adopcions_controller.rb
class AdopcionsController < ApplicationController
    # before_action :set_adopcion, only: [:show, :edit, :update, :destroy]
    layout 'clientes'

    def index
      # @adopciones = Adopcion.all
      @adopciones = Adopcion.order(:estado)
      if current_user
        render(:layout => "layouts/clientes")
      else
        render(:layout => "layouts/base")
      end
    end

    def show
    end

    def new
      @adopcion = Adopcion.new
    end

    # def new_mi_perro
    #   @perros = Perro.where(persona_id: params[:id])
    # end
    
    #   def create_mi_perro
    #     perro_id = params[:perro_id]
    #     @perro = Perro.find(perro_id)

    #     adopcion = Adopcion.new(
    #       # tamanio: @perro,
    #       otro_parametro: valor,
    #       # ... otros parámetros ...
    #     )
    #     @adopcion.estado ||= "Publicado"
    #     if @adopcion.save
    #       redirect_to "/adopciones", notice: 'Perro publicado correctamente en adopción.'
    #     else
    #       render :new
    #     end
    #   end

    def create
      @adopcion = Adopcion.new(adopcion_params)
      @adopcion.estado ||= "Publicado"
      if @adopcion.save
        redirect_to "/adopciones", notice: 'Perro publicado correctamente en adopción.'
      else
        render :new
      end
    end

    def adopcionesVisitante
      @adopciones = Adopcion.all
      render(:layout => "layouts/base")
    end

    def mis_publicaciones
      @publicaciones = Adopcion.where(persona_id: current_user.persona.id)
      render(:layout => "layouts/clientes")
    end

    def adoptar
      @publicacion = Adopcion.find(params[:id])
      render(:layout => "layouts/base")
    end

    def adoptar_datos
      @publicacion_id = params[:id]
      @adopcion = Adopcion.find(@publicacion_id)
      if  params[:email].blank? ||  params[:telefono].blank? ||  params[:nombre].blank? || params[:apellido].blank?
        flash[:alert] = 'Por favor complete todos los campos.'
        puts "parametro:  #{params[:email]}"
        flash[:input_params] = {
          email: params[:email],
          telefono: params[:telefono],
          nombre: params[:nombre],
          apellido: params[:apellido],
          razon: params[:razon]
        }
        puts "parametro:  #{flash[:input_params][:email]}"

        redirect_back(fallback_location: root_path(id: @publicacion_id))
      else
        @duenio= Persona.find(@adopcion.persona_id)
        @usuarioDuenio=User.find(@duenio.user_id)
        UserMailer.adopcion_contactar(User.new(email: @usuarioDuenio.email), @duenio.nombre, @duenio.apellido,
        params[:nombre], params[:apellido], params[:telefono], params[:email], params[:razon], @adopcion).deliver
        flash[:notice] = 'Email Enviado. A la brevedad serás contactado por el dueño de la publicación.'
        redirect_to "/adopciones"
      end
    end

    def marcar_adoptado
      @publicacion = Adopcion.find(params[:id])
      if @publicacion.update_columns(estado: "Adoptado")
        redirect_to adopciones_index_path, notice: '¡El perro fue marcado como adoptado!.'
      else
        redirect_to adopciones_index_path, alert: 'Error al marcar como adoptado el perro.'
      end
    end

    private

    def set_adopcion
      @adopcion = Adopcion.find(params[:id])
    end

    def adopcion_params
      params.require(:adopcion).permit(:tipo_raza_id, :sexo, :tamanio, :origen, :estado, :persona_id)
    end

end

app/views/adopcions/index.html.erb
<!--
  Esta vista la tienen todos
  Se ven las adopciones de adopción
-->

<% content_for :titulo do %>
  <br><br><br>
  <div style="display: flex; align-items: center; text-align: center;">
    <i class="material-icons small left grey" style="margin-right: 10px;">pets</i>
    <h2 style="margin-top: 4px; font-weight: 200; margin-bottom: 0;">&nbsp; Perros en adopción</h2>
  </div>
<% end %>

<% content_for :titulo_acciones do %>
  <br>
    <% if current_user %>
    <%# <a class="btn btn-primary anchor-new-celeste" href= "<%= adopciones_publicacion_new_mi_perro_path(id: current_user.persona.id) %>
      <%# style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:100%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center; margin-top: 20%;">  %>
      <%# Publicar mis perros  %>
      <%# <i class="material-icons" style="margin-left:15px;">add</i>  %>
      <%# <i class="material-icons" style="margin-left:15px;">pets</i>  %>
    <%# </a>   %>
    <a class="btn btn-primary anchor-new-celeste" href= "<%= adopciones_publicacion_new_path(id: current_user.persona.id) %>"
      style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:100%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center; margin-top: 20%;">
      Publicar un perro
      <i class="material-icons" style="margin-left:15px;">add</i>
      <i class="material-icons" style="margin-left:15px;">pets</i>
    </a>
  <% end %>
  <br>
<% end %>

<% content_for :body do %>
  <% if current_user %>
    <a class="btn btn-primary anchor-new-celeste" href="<%= adopciones_mis_publicaciones_path(id: current_user.persona.id) %>"
      style="background-color: rgb(252, 145, 14); border: none; border-radius: 2px; width: 20%; letter-spacing: 0.5px; vertical-align: center; display: flex; align-items: center; justify-content: center;">
      Mis publicaciones
      <i class="material-icons" style="margin-left: 15px;">visibility</i>
    </a>
  <% end %>
  <% if @adopciones.any? %>
    <% if !current_user %>
      <div class="col-md-8 mx-auto">
    <% end %>
    <div class="card" style="border-radius:0;">
      <div class="card-content">
        <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
          <thead>
            <tr>
              <th scope="col">Sexo</th>
              <th scope="col">Tamaño</th>
              <th scope="col">Raza</th>
              <th scope="col">Origen</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @adopciones.each do |adopcion| %>
              <% if adopcion.estado == "Publicado" %>
                <tr>
                  <td><%= adopcion.sexo %></td>
                  <td><%= adopcion.tamanio %></td>
                  <td><%= adopcion.tipo_raza.nombre %></td>
                  <td><%= adopcion.origen %></td>
                  <td>
                    <% if user_signed_in? && current_user.persona.id == adopcion.persona_id %>
                      <%= form_with(url: marcar_adoptado_path(adopcion.id), method: :post, class: 'confirm-form') do |form| %>
                        <button type="submit" class="btn-link" style="background:none; border:none; color: green;" data-bs-toggle="tooltip" data-bs-placement="top" title="Marcar como adoptado">
                          <i class="material-icons">check</i>
                        </button>
                      <% end %>
                    <% else %>
                      <%= link_to mail_adopcion_path(adopcion) do %>
                          <i class="material-icons" data-bs-toggle="tooltip" data-bs-placement="top" title="Me interesa adoptar el perro">mail</i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% else %>
                <tr>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= adopcion.sexo %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= adopcion.tamanio %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= adopcion.tipo_raza.nombre %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= adopcion.origen %></td>
                  <td style="color:darkgreen; background-color: rgba(200, 247, 197);, 1">
                    ¡Adoptado!
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% if !current_user %>
    </div>
  <% end %>
  <% else %>
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="card" style="border-radius: 0; position: relative; min-height: 100px;">
            <div class="card-content" style="position: relative; margin-bottom: 0;">
              <h4 class="mt-3">No hay perros registrados en adopción</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <br>
  <% if current_user %>
    <a class="btn btn-primary btn-volver" href="/homeCliente"
        style="margin-left:2%; background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
        Volver
        <i class="material-icons" style="margin-left:15px;">undo</i>
    </a>
  <% else %>
    <a class="btn btn-primary btn-volver" href="/"
        style="margin-left:6%; background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
        Volver
        <i class="material-icons" style="margin-left:15px;">undo</i>
    </a>
  <% end %>

   <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   <script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    });

   document.addEventListener('DOMContentLoaded', function() {
      const forms = document.querySelectorAll('.confirm-form');
      forms.forEach(form => {
        form.addEventListener('submit', function(event) {
          event.preventDefault(); // Evita el envío automático del formulario

          Swal.fire({
            title: '¿Estás seguro?',
            text: 'Esto marcará al perro como adoptado y la gente ya no se contactará por él.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#3085d6',
            confirmButtonText: 'Sí, estoy seguro'
          }).then((result) => {
            if (result.isConfirmed) {
              // Si el usuario confirma, envía el formulario
              form.submit();
            }
          });
        });
      });
    });
  </script>
<% end %>

app/views/adopcions/mis_publicaciones.html.erb
<% content_for :titulo do %>
  <br><br><br>
  <div style="display: flex; align-items: center; text-align: center;">
    <i class="material-icons small left grey" style="margin-right: 10px;">pets</i>
    <h2 style="margin-top: 4px; font-weight: 200; margin-bottom: 0;">&nbsp; Mis perros en adopción</h2>
  </div>
<% end %> 

<% content_for :body do %>
  <% if @publicaciones.any? %>
    <div class="card" style="border-radius:0;">
      <div class="card-content">
        <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
          <thead>
            <tr>
              <th scope="col">Sexo</th>
              <th scope="col">Tamaño</th>
              <th scope="col">Raza</th> 
              <th scope="col">Origen</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @publicaciones.each do |publicacion| %>
              <% if publicacion.estado == "Publicado" %>
                <tr>
                  <td><%= publicacion.sexo %></td>
                  <td><%= publicacion.tamanio %></td>
                  <td><%= publicacion.tipo_raza.nombre %></td>
                  <td><%= publicacion.origen %></td>
                  <td>
                    <% if user_signed_in? && current_user.persona.id == publicacion.persona_id %>
                        <%= form_with(url: marcar_adoptado_path(publicacion.id), method: :post, class: 'confirm-form') do |form| %>
                          <button type="submit" class="btn-link" style="background:none; border:none; color: green;" data-bs-toggle="tooltip" data-bs-placement="top" title="Marcar como adoptado">
                            <i class="material-icons">check</i>
                          </button>
                        <% end %>
                    <% end %>
                  </td>
                </tr> 
              <% else %>
                <tr>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= publicacion.sexo %></td> 
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= publicacion.tamanio %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= publicacion.tipo_raza.nombre %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= publicacion.origen %></td>
                  <td style="color:darkgreen; background-color: rgba(200, 247, 197);, 1">
                    ¡Adoptado!
                  </td>
                </tr> 
              <% end %>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  <% else %>
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="card" style="border-radius: 0; position: relative; min-height: 100px;">
            <div class="card-content" style="position: relative; margin-bottom: 0;">
              <h4 class="mt-3">No tenés perros registrados en adopción</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <br>
  <a class="btn btn-primary btn-volver" href="/adopciones"
    style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>

   <script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    });
  </script>
<% end %>

app/views/adopcions/new.html.erb
<!--
  Esta vista la tiene el cliente
  Es el formulario para hacer una publicación de un perro en adopción
-->

<% content_for :titulo do %>
  <div style="display: flex; align-items: center; margin-top:10%;" >
    <i class="material-icons medium left grey" style="margin-right: 10px;">person</i>
    <h2 style="margin-top: 4px; font-weight: 200;"> Publicar un perro </h2>
  </div>
<% end %> 

<% content_for :body do %>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-11">
        <div class="card" style="border-radius:0;">
          <div class="card-content">
    
            <%= form_with(model: @adopcion, url: adopciones_post_publicacion_new_path, local: true) do |f| %>

                <div class="d-flex justify-content-center align-items-center" style="margin-top: 1%;">
                    <div class="field" style="margin-right:4%;">
                    <%= f.collection_select :tipo_raza_id, TipoRaza.all, :id, :nombre, prompt: "Raza" %> 
                    </div>

                    <div class="field" >
                        <%= f.collection_select(:sexo, Adopcion.sexos.keys, :to_s, :humanize, prompt: "Sexo") %>
                    </div>
                </div>
                
                <div class="d-flex justify-content-center align-items-center" style="margin-top:4%;">
                    <div class="field" style="margin-right:30px;">
                        <%= f.label :origen %>
                        <%= f.text_field :origen, placeholder: 'Origen', class: 'form-control' %>
                    </div>

                    <div class="field">
                        <%= f.label :tamaño %><br>
                        <%= f.collection_select(:tamanio, Adopcion.tamanios.keys, :to_s, :humanize, prompt: "Tamaño") %>
                    </div>
                </div>

                <%= f.hidden_field :persona_id, value: current_user.persona.id %>

               

                <div class="d-flex justify-content-center align-items-center" style="min-height: 100px;">
                    <div class="actions">
                    <%= f.submit 'Publicar Perro', class: 'btn btn-primary', style: 'background-color: rgb(252, 145, 14); border: none; border-radius: 2px; width: 200px; height: 35px; letter-spacing: 0.5px; color: white;' %>
                    </div>
                </div>
                <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

  <a class="btn btn-primary btn-volver" href="/adopciones"
    style="background-color: rgb(252, 145, 14);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>
  
<% end %>

app/views/adopcions/new_mi_perro.erb
<% content_for :titulo do %>
  <br><br><br>
  <div style="display: flex; align-items: center; text-align: center;">
    <i class="material-icons small left grey" style="margin-right: 10px;">pets</i>
    <h2 style="margin-top: 4px; font-weight: 200; margin-bottom: 0;">&nbsp; Dar en adopción uno de mis Perros</h2>
  </div>
<% end %>

<% content_for :body do %>
   <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-9">
        <div class="card" style="border-radius:0;">
          <div class="card-content">
            <%= form_tag({ controller: 'adopcions', action: 'create_mi_perro' }, method: 'post') do %>
              <div class="d-flex justify-content-center align-items-center" style="margin-top:25px;">
                  <div class="field" style="margin-right:30px;">
                    <%= select_tag :perro_id, options_from_collection_for_select(@perros, 'id', 'nombre'), prompt: "Selecciona un perro" %>
                  </div>    
              </div>

              
              <div class="d-flex justify-content-center align-items-center" style="min-height: 100px;">
                <div class="actions">
                  <%= submit_tag 'Poner en adopción' , class: 'btn btn-primary', style: 'background-color: rgb(252, 145, 14); border: none; border-radius: 2px; width: 200px; height: 35px; letter-spacing: 0.5px; color: white;'%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>