config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/homeVeterinario' => "veterinarios#homeVeterinario"
  get '/homeClientes' => "clientes#homeClientes"

  # get '/registrarCliente', to: 'personas#new_user_and_persona'
  get '/registrarCliente', to: 'personas#new_user_and_persona', as: 'new_user_and_persona'
  post '/registrarCliente', to: 'personas#create_user_and_persona'

  get '/mi_perfil/:id', to: 'personas#show_mydata', as: 'show_my_data'

  get '/personas/:persona_id/perros/personaperro', to: 'perros#personaperro', as: 'persona_perros_personaperro'
  get '/personas/:id/datos_personales', to: 'personas#datos_personales', as: 'persona_datos_personales'

  get '/index/:id/ver_info_perro', to: 'perros#ver_info_perro', as: 'ver_info_perro'

  get '/turnos_del_dia', to: 'turnos#turnos_del_dia', as: 'turnos_del_dia'

  get 'turnos/:id/aceptar', to: 'turnos#aceptar', as: 'aceptar_turno'
  post 'procesar_aceptar/:id', to: 'turnos#procesar_aceptar', as: 'procesar_aceptar_turno'
  get 'turnos/:id/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'procesar_rechazar/:id', to: 'turnos#procesar_rechazar', as: 'procesar_rechazar_turno'

  post 'perroEncontrado/:id', to: 'perdido_encontrados#marcar_encontrado', as: 'marcar_encontrado'

  get 'turnos_del_dia/:id', to: 'turnos#ausente', as: 'ausente_turno'
  get 'turnos_del_dia/:id/presente', to: 'turnos#presente', as: 'presente_turno'
  # resources :tipo_turnos
  get '/index/:id/ver_info_perro/historia_clinica', to: 'perros#historia_clinica', as: 'historia_clinica_perro'
  get '/index/:id/ver_info_perro/libreta_sanitaria', to: 'perros#libreta_sanitaria', as: 'libreta_sanitaria_perro'

  get '/personas/:id/editar', to: 'personas#editar', as: 'personas_editar'
  patch '/personas/:id/editar', to: 'personas#update', as: 'actualizar_mi_perfil'

  get '/turnos/subirUrgencia', to: 'turnos#newUrgencia', as: 'new_urgencia'
  post '/turnos/subirUrgencia', to: 'turnos#createUrgencia'

  get '/turnosAll', to: 'turnos#mostrarTodos', as: 'turnos_todos'

  get '/nueva_campania', to: 'campania_donacions#new', as: 'nueva_campania'
  post '/crear_campania', to: 'campania_donacions#create', as: 'crear_campania'

  get '/vista_veterinario', to: 'campania_donacions#vistaVeterinario', as: 'vista_veterinario'

  get '/editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'

  get '/ver_campanias', to: 'campania_donacions#vistaUsuario', as: 'ver_campanias'

  get '/ver_campanias_publico', to: 'campania_donacions#vistaPublica', as: 'ver_campanias_publico'

  get '/ver_campanias/:id/donar', to: 'tarjeta_creditos#donar', as: 'donar'
  get '/ver_campanias/:id/donarVisitante', to: 'tarjeta_creditos#donarVisitante', as: 'donar_visitante'
  # post 'campanias/:id/procesar_donacion', to: 'campanias#procesar_donacion', as: 'procesar_donacion_campania'
  post '/procesar_dono', to: 'tarjeta_creditos#procesar_dono', as: 'procesar_dono'
  post '/procesar_visitante', to: 'tarjeta_creditos#procesar_dono_visitante', as: 'procesar_dono_visitante'

  get '/historial_gastos', to: 'turnos#historial_gastos', as: 'historial_gastos'

  get '/get_perros_by_persona', to: 'turnos#get_perros_by_persona'

  get '/ver_paseadores_publico', to: 'paseadors#index_paseador_guest', as: 'index_paseador_guest'

  get '/ver_paseadores', to: 'paseadors#index_paseador_usuario', as: 'index_paseador_usuario'

  get '/ver_paseadores_veterinario', to: 'paseadors#index_paseador_veterinario', as:'index_paseador_veterinario'

  # get '/nuevo_paseador', to: 'paseadors#new', as: 'nuevo_paseador'
  # post '/crear_paseador', to: 'paseadors#create', as: 'crear_paseador'

  get '/newPaseador', to: 'paseadors#newPaseador', as: 'new_paseador'
  post '/create_paseador', to: 'paseadors#createPaseador', as: 'create_paseador'
  get '/newCuidador', to: 'paseadors#newCuidador', as: 'new_cuidador'
  post '/create_cuidador', to: 'paseadors#createCuidador', as: 'create_cuidador'

  get '/perdido_encontrado_nuevo', to: 'perdido_encontrados#new', as: 'nuevo_perdido_encontrado'
  post '/crear_perdido_encontrado', to: 'perdido_encontrados#create', as: 'crear_perdido_encontrado'

  get '/encontrado_nuevo', to: 'encontrados#new', as: 'nuevo_encontrado'
  post '/crear_encontrado', to: 'encontrados#create', as: 'crear_encontrado'
  resources :encontrados

  get '/perdido_encontrado_usuario', to: 'perdido_encontrados#perdido_encontrado_usuario', as:'perdido_encontrado_usuario'

  get '/encontrado_usuario', to: 'encontrados#index_encontrado_usuario', as:'index_encontrado_usuario'

  get '/perdido_encontrado_visitante', to: 'perdido_encontrados#perdido_encontrado_visitante', as: 'perdido_encontrado_visitante'

  get '/perdido_mis_publicaciones', to: 'perdido_encontrados#mis_publicaciones_perdidos', as: 'mis_publicaciones_perdidos'

  get '/mis_publicaciones_encontrados', to: 'encontrados#mis_publicaciones_encontrados', as: 'mis_publicaciones_encontrados'

  get '/vista_visitantes_encontrados', to: 'encontrados#index_encontrado_visitante', as: 'index_encontrado_visitante'

  get '/paseadores/:id/editar', to: 'paseadors#edit', as: 'paseadors_editar'
  patch '/paseadores/:id/editar', to: 'paseadors#update', as: 'actualizar_paseadors'

  get '/perdidos/reencuentros', to: 'perdido_encontrados#show_reencuentros', as: 'perros_perdidos_y_encontrados'

  # patch '/mi_perfil/:id/actualizar', to: 'personas#update', as: 'actualizar_mi_perfil'

  resources :campania_donacions, only:[:new, :create, :vistaVeterinario, :editar, :update, :vistaUsuario]

  resources :perdido_encontrados, only:[:new, :create, :perdido_encontrado_usuario, :perdido_encontrado_visitante, :mis_publicaciones_perdidos]

  resources :encontrados, only:[:new, :create, :index_encontrado_usuario, :mis_publicaciones_encontrados, :index_encontrado_visitante]

  resources :paseadors, only:[:new, :create, :index_paseador_guest, :index_paseador_usuario, :index_paseador_veterinario, :edit, :update]

  resources :tarjeta_creditos, only:[:new, :index, :create, :edit, :update, :destroy, :informacion_correcta, :donar]

  resources :perros, only: [:new, :create, :index, :personaperro, :ver_info_perro]

  resources :turnos, only: [:new, :create, :show, :index, :turnos_del_dia, :update, :historial_gastos, :get_perros_by_persona]

  resources :personas, only: [:new, :create, :index, :editar, :update]

  resources :personas, only: [:new, :create, :index, :edit, :update] do
    resources :perros, only: [:personaperro, :new, :create]  # Agrega ruta anidada solo para la acción index de perros
  end

  post '/personas/:id/baja', to: 'veterinarios#baja_logica_cliente', as: 'baja_persona'
  post '/perros/:id/baja', to: 'personas#baja_logica_perro', as: 'baja_perro'

  get '/under_construction', to: 'application#under_construction'

  get '/turnos/:id/historiaClinica', to: 'turnos#show_turno_historiaClinica', as: 'show_turno_historia'
  get '/turnos/:id/libretaSanitaria', to: 'turnos#show_turno_libretaSanitaria', as: 'show_turno_libreta'

  get '/adopciones', to: 'adopcions#index', as: 'adopciones_index'
  # get '/home/adopciones', to: 'adopcions#adopcionesVisitante', as: 'adopciones_index_visitante'

  get '/adopciones/publicar/:id', to: 'adopcions#new', as: 'adopciones_publicacion_new'
  post 'adopciones/publicar', to: 'adopcions#create', as: 'adopciones_post_publicacion_new'
  get '/adopciones/:id/publicaciones', to: 'adopcions#mis_publicaciones', as: 'adopciones_mis_publicaciones'

  get '/adopciones/publicar_mi_perro/:id', to: 'adopcions#new_mi_perro', as: 'adopciones_publicacion_new_mi_perro'
  post 'adopciones/publicar_mi_perro', to: 'adopcions#create_mi_perro', as: 'adopciones_post_publicacion_new_mi_perro'
  resources :adopcions  # Add this line

  get '/adopciones/:id/contactar', to: 'adopcions#adoptar', as: 'mail_adopcion'
  post '/adopciones/:id/contactar', to: 'adopcions#adoptar_datos'

  post '/adopciones/:id/adoptado', to: 'adopcions#marcar_adoptado', as: 'marcar_adoptado'
  post '/encontrados/:id/recuperado', to: 'encontrados#marcar_recuperado', as: 'marcar_recuperado'

  #root to: 'application#home'
  root 'application#determine_root'

  # match "*path", to: "application#under_construction", via: :all
end

app/models/campania_donacion.rb
class CampaniaDonacion < ApplicationRecord
  validate :fecha_final_valida
  validates :nombre, presence: { message: "El campo está vacío" }
  validates :descripcion, presence: { message: "El campo está vacío" }

  # Nuevos campos
  validates :monto_actual, numericality: { greater_than_or_equal_to: 0, message: "Debe ser un número no negativo" }
  validates :monto_objetivo, numericality: { greater_than_or_equal_to: 0, message: "Debe ser un número no negativo" }

  private

  def fecha_final_valida
    if fecha_final.present? && fecha_final < DateTime.now
      errors.add(:fecha_final, "La fecha final debe ser para un día futuro.")
    end
  end
end

app/controllers/campania_donacions_controller.rb
class CampaniaDonacionsController < ApplicationController

  before_action :authenticate_user!, except: [:vistaPublica]  #Esto me muestra el cartel que luego hay que poner lindo
  before_action :authorize_admin, only: [:new, :create, :editar, :update, :vistaVeterinario]
  before_action :authorize_client, only: [:vistaUsuario]
  layout 'veterinarios', only: [:new, :create, :editar, :update, :vistaVeterinario]
  layout 'veterinarios', except: [:vistaUsuario]
  #layout 'clientes', only: [:vistaUsuario]

  def authorize_admin
    unless current_user && current_user.role == "admin"
      redirect_to root_path, alert: "No tenés permiso para acceder a esta página."
    end
  end

  def authorize_client
    unless current_user && current_user.role == "cliente"
      redirect_to root_path, alert: "No tenés permiso para acceder a esta página."
    end
  end

  def vistaUsuario
    @campanias = CampaniaDonacion.all
    render(:layout => "layouts/clientes")
  end

  def vistaVeterinario
    @campanias = CampaniaDonacion.all
    render(:layout => "layouts/veterinarios")
  end

  def vistaPublica
   @campanias = CampaniaDonacion.all
   render(:layout => "layouts/base")
  end


   def new
     @campania = CampaniaDonacion.new
     render(:layout => "layouts/veterinarios")
   end

   def create
     @campania = CampaniaDonacion.new(campania_donacion_params)
     if @campania.save
       redirect_to vista_veterinario_path, notice: 'Campaña de donación creada con éxito.'
     else
      #redirect_to nueva_campania_path #, notice: 'Campaña no se pudo crear.'
      render 'new'
     end
   end

  def editar
    @campania = CampaniaDonacion.find(params[:id])
    render(:layout => "layouts/veterinarios")
  end

  def update
    @campania = CampaniaDonacion.find(params[:id])
    if @campania.update(campania_donacion_params)
      redirect_to vista_veterinario_path, notice: 'Perfil actualizado exitosamente.'
    else
      puts @campania.errors.full_messages.inspect
      render :editar
    end
  end



  private

  def campania_donacion_params
    params.require(:campania_donacion).permit(:nombre, :descripcion, :fecha_final, :monto_actual, :monto_objetivo)
  end

end

app/views/campania_donacions/editar.html.erb
<!-- 
    Esta vista es para editar las campañas ya creadas
-->
<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 50px;">
    <i class="material-icons small left grey" style="margin-right: 10px;">edit</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Editar Campaña </h2>
</div>
<% end %>

<% content_for :body do %>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-11">
        <div class="card" style="border-radius:0;">
          <div class="card-content">
            <%= form_with(model: @campania, url: campania_donacion_path(@campania), method: :patch) do |form| %>
              
              <% if @campania.errors.any? %>
                <div class="alert alert-danger">
                  <h4><%= pluralize(@campania.errors.count, "error") %> prohibió que esta campaña se guarde:</h4>
                  <ul>
                    <% @campania.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-right:20%;">
                  <div class="form-group">
                    <%= form.label :nombre %>
                    <%= form.text_field :nombre, class: 'form-control', style: 'width: 150%;' %>
                  </div>
                </div>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top: 4%;">
                  <div class="form-group">
                    <%= form.label :fecha_final %>
                    <%= form.datetime_select :fecha_final, class: 'form-control' %>
                  </div>
                </div>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top: 4%;">
                  <div class="form-group">
                    <%= form.label :monto_actual %>
                    <%= form.text_field :monto_actual, class: 'form-control', style: 'width: 200%;' %>
                  </div>
                </div>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top: 4%;">
                  <div class="form-group">
                    <%= form.label :monto_objetivo %>
                    <%= form.text_field :monto_objetivo, class: 'form-control', style: 'width: 200%;' %>
                  </div>
                </div>
              </div>

              <div class="form-group" style="margin-top: 3%;">
                <%= form.label :descripcion, style: 'margin-left:10%;' %>
                <%= form.text_area :descripcion, class: 'form-control', style: 'width:80%; margin-left:10%;' %>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top:4%;">
                  <%= form.submit 'Guardar Cambios', class: 'btn btn-primary', class: 'btn btn-primary', style: 'background-color: rgb(28, 150, 174); border: none; border-radius: 2px; width: 200px; height: 35px; letter-spacing: 0.5px; color: white;' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

    <%= link_to 'Cancelar', vista_veterinario_path, class: 'btn btn-secondary' %>

<% end %>

app/views/campania_donacions/new.html.erb
<!-- 
    Creacion de campañas, se ingresan todos los datos basicos para crearla
-->

<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 50px;">
    <i class="material-icons medium left grey" style="margin-right: 10px;">campaign</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Nueva Campaña de donacion</h2>
</div>
<% end %>

<% content_for :body do %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-11">
        <div class="card" style="border-radius:0;">
          <div class="card-content">
            <%= form_with(model: @campania, url: campania_donacions_path, method: :post) do |form| %>

              <% if @campania.errors.any? %>
                <div class="alert alert-danger">
                  <h4><%= pluralize(@campania.errors.count, "error") %> prohibió que esta campaña se guarde:</h4>
                  <ul>
                    <% @campania.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-right:20%;">
                  <%= form.label :nombre %>
                  <%= form.text_field :nombre, class: 'form-control', placeholder: 'Nombre de la Campaña', style: 'width: 150%;' %>
                  <% if @campania.errors[:nombre].any? %>
                    <div class="error-message">
                      <%= @campania.errors[:nombre].first %>
                    </div>
                  <% end %>
                </div>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top: 4%;">
                  <%= form.label :fecha_final %>
                  <%= form.datetime_select :fecha_final, class: 'form-control' %>
                  <% if @campania.errors[:fecha_final].any? %>
                    <div class="error-message">
                      <%= @campania.errors[:fecha_final].first %>
                    </div>
                  <% end %>
                </div>
              </div>

              <div class="form-group" style="margin-top: 3%;">
                <%= form.label :descripcion, style: 'margin-left:10%;'%>
                <%= form.text_area :descripcion, class: 'form-control', placeholder: 'Descripción de la Campaña', style: 'width:80%; margin-left:10%;' %>
                <% if @campania.errors[:descripcion].any? %>
                  <div class="error-message" style="margin-left:10%;">
                    <%= @campania.errors[:descripcion].first %>
                  </div>
                <% end %>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top: 4%; margin-right:5%;">
                  <%= form.label :monto_actual %>
                  <%= form.text_field :monto_actual, class: 'form-control', placeholder: 'Monto Actual', style: 'width: 110%;' %>
                  <% if @campania.errors[:monto_actual].any? %>
                    <div class="error-message">
                      <%= @campania.errors[:monto_actual].first %>
                    </div>
                  <% end %>
                </div>
                <div class="form-group" style="margin-top: 4%;">
                  <%= form.label :monto_objetivo %>
                  <%= form.text_field :monto_objetivo, class: 'form-control', placeholder: 'Monto Objetivo', style: 'width: 110%;' %>
                  <% if @campania.errors[:monto_objetivo].any? %>
                    <div class="error-message">
                      <%= @campania.errors[:monto_objetivo].first %>
                    </div>
                  <% end %>
                </div>
              </div>

              <div class="d-flex justify-content-center align-items-center">
                <div class="form-group" style="margin-top:4%;">
                  <%= form.submit 'Guardar Campaña', class: 'btn btn-primary', class: 'btn btn-primary', style: 'background-color: rgb(28, 150, 174); border: none; border-radius: 2px; width: 200px; height: 35px; letter-spacing: 0.5px; color: white;' %>
                </div>
              </div>
            <% end %>
           </div>
        </div>
      </div>
    </div>
  </div>

  <%# <%= link_to 'Volver', vista_veterinario_path, class: 'btn btn-secondary' %>
   <a class="btn btn-primary btn-volver d-print-none " href="/vista_veterinario"
      style="background-color: rgb(28, 150, 174);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
      Volver
      <i class="material-icons" style="margin-left:15px;">undo</i>
    </a>
<% end %>

app/views/campania_donacions/vistaUsuario.html.erb
<!-- esta vista es para los usuarios registrados que pueden ver las campañas creadas
contiene boton de volver
-->

<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 8%;">
    <i class="material-icons medium left grey" style="margin-right: 10px;">campaign</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Campañas de Donación</h2>
  </div>
<% end %>

<% content_for :body do %>

  <div class="row">
  <% @campanias.each do |campania| %>
    <div class="col-md-4">
      <div class="card<%= ' finalizada' if campania.fecha_final && campania.fecha_final < DateTime.now %>">
        <div class="card-body">
          <h5 class="card-title<%= ' finalizada' if campania.fecha_final && campania.fecha_final < DateTime.now %>">
            <%= campania.nombre %>
            <% if campania.fecha_final && campania.fecha_final < DateTime.now %>
              - Finalizada
            <% end %>
          </h5>
          <p class="card-text"><%= campania.descripcion %></p>
          <p class="card-text">Fecha Final: <%= campania.fecha_final.strftime('%d/%m/%Y - %H:%M') %></p>
          
          <% if campania.monto_actual.present? %>
            <p class="card-text">Monto Actual: <%= number_to_currency(campania.monto_actual, unit: '$', separator: ',', delimiter: '.') %></p>
          <% end %>

          <% if campania.monto_objetivo.present? %>
            <p class="card-text">Monto Objetivo: <%= number_to_currency(campania.monto_objetivo, unit: '$', separator: ',', delimiter: '.') %></p>
          <% end %>

          <% if campania.fecha_final && campania.fecha_final > DateTime.now %>
            <%= link_to 'Donar', donar_path(campania), class: 'btn btn-primary btn-donar', style: 'background-color: rgb(28, 150, 174); border: none; border-radius: 2px; width: 100%; letter-spacing: .5px; vertical-align: center; display: flex; align-items: center; justify-content: center; margin-top: 10px;' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

  
  </div>


  <br>
  <%= link_to 'Volver', root_path, class: 'btn btn-primary btn-volver', style:'background-color: rgb(28, 150, 174);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center' %>

<% end %>

app/views/campania_donacions/vistaVeterinario.html.erb
<!-- vista de todas las campañas del veterinario que creo
contiene un boton para crear una nueva campaña

-->
<% content_for :titulo do %>
  <div style="display: flex; align-items: center; justify-content: center; margin-top: 6%;">
    <i class="material-icons medium left grey" style="margin-right: 10px;">campaign</i>
    <h2 style="margin-top: 4px; font-weight: 200;">Campañas de donación</h2>
  </div>
<% end %>

<% content_for :titulo_acciones do %>
  <a class="btn btn-primary anchor-new-celeste" href="/nueva_campania"
    style="background-color: rgb(28, 150, 174);border: none; border-radius:2px; width:100%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center; margin-top: 20%;">
    Nueva Campaña
    <i class="material-icons" style="margin-left:15px;">add</i>
    <i class="material-icons" style="margin-left:15px;">campaign</i>
  </a>
  <br>
      <%# <%= link_to 'Nueva Campaña', nueva_campania_path, class: 'btn btn-primary'%>
<% end %>

<% content_for :body do %>

    <div class="card" style="border-radius:0;">
      <div class="card-content">
        <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Descripción</th>
              <th>Monto Actual</th>
              <th>Monto Objetivo</th>
              <th>Fecha Final</th>
              <th>Editar</th> 
            </tr>
          </thead>
          <tbody>
            <% @campanias.each do |campania| %>
              <tr>
                <td><%= campania.nombre %></td>
                <td><%= campania.descripcion %></td>
                <td><%= number_to_currency(campania.monto_actual, unit: '$', separator: ',', delimiter: '.') if campania.monto_actual.present? %></td>
                <td><%= number_to_currency(campania.monto_objetivo, unit: '$', separator: ',', delimiter: '.') if campania.monto_objetivo.present? %></td>
                <td><%= campania.fecha_final.strftime('%d-%m-%Y %H:%M') %></td>
                <td>
                  <%= link_to editar_campania_path(campania) do %>
                     <i class="material-icons" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar Campaña">edit</i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <br>
    <a class="btn btn-primary btn-volver" href="/homeVeterinario"
      style="background-color: rgb(28, 150, 174);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
      Volver
      <i class="material-icons" style="margin-left:15px;">undo</i>
    </a>

    <script>
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
        return new bootstrap.Tooltip(tooltipTriggerEl)
      });
    </script>

<% end %>