config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/homeVeterinario' => "veterinarios#homeVeterinario"
  get '/homeClientes' => "clientes#homeClientes"

  # get '/registrarCliente', to: 'personas#new_user_and_persona'
  get '/registrarCliente', to: 'personas#new_user_and_persona', as: 'new_user_and_persona'
  post '/registrarCliente', to: 'personas#create_user_and_persona'

  get '/mi_perfil/:id', to: 'personas#show_mydata', as: 'show_my_data'

  get '/personas/:persona_id/perros/personaperro', to: 'perros#personaperro', as: 'persona_perros_personaperro'
  get '/personas/:id/datos_personales', to: 'personas#datos_personales', as: 'persona_datos_personales'

  get '/index/:id/ver_info_perro', to: 'perros#ver_info_perro', as: 'ver_info_perro'

  get '/turnos_del_dia', to: 'turnos#turnos_del_dia', as: 'turnos_del_dia'

  get 'turnos/:id/aceptar', to: 'turnos#aceptar', as: 'aceptar_turno'
  post 'procesar_aceptar/:id', to: 'turnos#procesar_aceptar', as: 'procesar_aceptar_turno'
  get 'turnos/:id/rechazar', to: 'turnos#rechazar', as: 'rechazar_turno'
  post 'procesar_rechazar/:id', to: 'turnos#procesar_rechazar', as: 'procesar_rechazar_turno'

  post 'perroEncontrado/:id', to: 'perdido_encontrados#marcar_encontrado', as: 'marcar_encontrado'

  get 'turnos_del_dia/:id', to: 'turnos#ausente', as: 'ausente_turno'
  get 'turnos_del_dia/:id/presente', to: 'turnos#presente', as: 'presente_turno'
  # resources :tipo_turnos
  get '/index/:id/ver_info_perro/historia_clinica', to: 'perros#historia_clinica', as: 'historia_clinica_perro'
  get '/index/:id/ver_info_perro/libreta_sanitaria', to: 'perros#libreta_sanitaria', as: 'libreta_sanitaria_perro'

  get '/personas/:id/editar', to: 'personas#editar', as: 'personas_editar'
  patch '/personas/:id/editar', to: 'personas#update', as: 'actualizar_mi_perfil'

  get '/turnos/subirUrgencia', to: 'turnos#newUrgencia', as: 'new_urgencia'
  post '/turnos/subirUrgencia', to: 'turnos#createUrgencia'

  get '/turnosAll', to: 'turnos#mostrarTodos', as: 'turnos_todos'

  get '/nueva_campania', to: 'campania_donacions#new', as: 'nueva_campania'
  post '/crear_campania', to: 'campania_donacions#create', as: 'crear_campania'

  get '/vista_veterinario', to: 'campania_donacions#vistaVeterinario', as: 'vista_veterinario'

  get '/editar_campania/:id', to: 'campania_donacions#editar', as: 'editar_campania'

  get '/ver_campanias', to: 'campania_donacions#vistaUsuario', as: 'ver_campanias'

  get '/ver_campanias_publico', to: 'campania_donacions#vistaPublica', as: 'ver_campanias_publico'

  get '/ver_campanias/:id/donar', to: 'tarjeta_creditos#donar', as: 'donar'
  get '/ver_campanias/:id/donarVisitante', to: 'tarjeta_creditos#donarVisitante', as: 'donar_visitante'
  # post 'campanias/:id/procesar_donacion', to: 'campanias#procesar_donacion', as: 'procesar_donacion_campania'
  post '/procesar_dono', to: 'tarjeta_creditos#procesar_dono', as: 'procesar_dono'
  post '/procesar_visitante', to: 'tarjeta_creditos#procesar_dono_visitante', as: 'procesar_dono_visitante'

  get '/historial_gastos', to: 'turnos#historial_gastos', as: 'historial_gastos'

  get '/get_perros_by_persona', to: 'turnos#get_perros_by_persona'

  get '/ver_paseadores_publico', to: 'paseadors#index_paseador_guest', as: 'index_paseador_guest'

  get '/ver_paseadores', to: 'paseadors#index_paseador_usuario', as: 'index_paseador_usuario'

  get '/ver_paseadores_veterinario', to: 'paseadors#index_paseador_veterinario', as:'index_paseador_veterinario'

  # get '/nuevo_paseador', to: 'paseadors#new', as: 'nuevo_paseador'
  # post '/crear_paseador', to: 'paseadors#create', as: 'crear_paseador'

  get '/newPaseador', to: 'paseadors#newPaseador', as: 'new_paseador'
  post '/create_paseador', to: 'paseadors#createPaseador', as: 'create_paseador'
  get '/newCuidador', to: 'paseadors#newCuidador', as: 'new_cuidador'
  post '/create_cuidador', to: 'paseadors#createCuidador', as: 'create_cuidador'

  get '/perdido_encontrado_nuevo', to: 'perdido_encontrados#new', as: 'nuevo_perdido_encontrado'
  post '/crear_perdido_encontrado', to: 'perdido_encontrados#create', as: 'crear_perdido_encontrado'

  get '/encontrado_nuevo', to: 'encontrados#new', as: 'nuevo_encontrado'
  post '/crear_encontrado', to: 'encontrados#create', as: 'crear_encontrado'
  resources :encontrados

  get '/perdido_encontrado_usuario', to: 'perdido_encontrados#perdido_encontrado_usuario', as:'perdido_encontrado_usuario'

  get '/encontrado_usuario', to: 'encontrados#index_encontrado_usuario', as:'index_encontrado_usuario'

  get '/perdido_encontrado_visitante', to: 'perdido_encontrados#perdido_encontrado_visitante', as: 'perdido_encontrado_visitante'

  get '/perdido_mis_publicaciones', to: 'perdido_encontrados#mis_publicaciones_perdidos', as: 'mis_publicaciones_perdidos'

  get '/mis_publicaciones_encontrados', to: 'encontrados#mis_publicaciones_encontrados', as: 'mis_publicaciones_encontrados'

  get '/vista_visitantes_encontrados', to: 'encontrados#index_encontrado_visitante', as: 'index_encontrado_visitante'

  get '/paseadores/:id/editar', to: 'paseadors#edit', as: 'paseadors_editar'
  patch '/paseadores/:id/editar', to: 'paseadors#update', as: 'actualizar_paseadors'

  get '/perdidos/reencuentros', to: 'perdido_encontrados#show_reencuentros', as: 'perros_perdidos_y_encontrados'

  # patch '/mi_perfil/:id/actualizar', to: 'personas#update', as: 'actualizar_mi_perfil'

  resources :campania_donacions, only:[:new, :create, :vistaVeterinario, :editar, :update, :vistaUsuario]

  resources :perdido_encontrados, only:[:new, :create, :perdido_encontrado_usuario, :perdido_encontrado_visitante, :mis_publicaciones_perdidos]

  resources :encontrados, only:[:new, :create, :index_encontrado_usuario, :mis_publicaciones_encontrados, :index_encontrado_visitante]

  resources :paseadors, only:[:new, :create, :index_paseador_guest, :index_paseador_usuario, :index_paseador_veterinario, :edit, :update]

  resources :tarjeta_creditos, only:[:new, :index, :create, :edit, :update, :destroy, :informacion_correcta, :donar]

  resources :perros, only: [:new, :create, :index, :personaperro, :ver_info_perro]

  resources :turnos, only: [:new, :create, :show, :index, :turnos_del_dia, :update, :historial_gastos, :get_perros_by_persona]

  resources :personas, only: [:new, :create, :index, :editar, :update]

  resources :personas, only: [:new, :create, :index, :edit, :update] do
    resources :perros, only: [:personaperro, :new, :create]  # Agrega ruta anidada solo para la acción index de perros
  end

  post '/personas/:id/baja', to: 'veterinarios#baja_logica_cliente', as: 'baja_persona'
  post '/perros/:id/baja', to: 'personas#baja_logica_perro', as: 'baja_perro'

  get '/under_construction', to: 'application#under_construction'

  get '/turnos/:id/historiaClinica', to: 'turnos#show_turno_historiaClinica', as: 'show_turno_historia'
  get '/turnos/:id/libretaSanitaria', to: 'turnos#show_turno_libretaSanitaria', as: 'show_turno_libreta'

  get '/adopciones', to: 'adopcions#index', as: 'adopciones_index'
  # get '/home/adopciones', to: 'adopcions#adopcionesVisitante', as: 'adopciones_index_visitante'

  get '/adopciones/publicar/:id', to: 'adopcions#new', as: 'adopciones_publicacion_new'
  post 'adopciones/publicar', to: 'adopcions#create', as: 'adopciones_post_publicacion_new'
  get '/adopciones/:id/publicaciones', to: 'adopcions#mis_publicaciones', as: 'adopciones_mis_publicaciones'

  get '/adopciones/publicar_mi_perro/:id', to: 'adopcions#new_mi_perro', as: 'adopciones_publicacion_new_mi_perro'
  post 'adopciones/publicar_mi_perro', to: 'adopcions#create_mi_perro', as: 'adopciones_post_publicacion_new_mi_perro'
  resources :adopcions  # Add this line

  get '/adopciones/:id/contactar', to: 'adopcions#adoptar', as: 'mail_adopcion'
  post '/adopciones/:id/contactar', to: 'adopcions#adoptar_datos'

  post '/adopciones/:id/adoptado', to: 'adopcions#marcar_adoptado', as: 'marcar_adoptado'
  post '/encontrados/:id/recuperado', to: 'encontrados#marcar_recuperado', as: 'marcar_recuperado'

  #root to: 'application#home'
  root 'application#determine_root'

  # match "*path", to: "application#under_construction", via: :all
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  layout 'clientes', except: [:newUrgencia, :createUrgencia, :turnos_del_dia, :aceptar, :rechazar, :mostrarTodos, :show_turno_historiaClinica, :show_turno_libretaSanitaria, :historial_gastos]
  layout 'veterinarios', only: [:newUrgencia, :createUrgencia, :turnos_del_dia, :aceptar, :rechazar, :mostrarTodos, :show_turno_historiaClinica, :show_turno_libretaSanitaria, :historial_gastos]

  before_action :authenticate_user! #Esto me muestra el cartel que luego hay que poner lindo
  before_action :authorize_admin, only: [:index, :newUrgencia, :turnos_del_dia, :historial_gastos]
  before_action :authorize_client, only: [:new]

  def authorize_admin
    unless current_user && current_user.role == "admin"
      redirect_to root_path, alert: "No tenés permiso para acceder a esta página."
    end
  end

  def authorize_client
    unless current_user && current_user.role == "cliente"
      redirect_to root_path, alert: "No tienes permiso para acceder a esta página."
    end
  end

  def index
    @turnos = Turno.where(estado: 'pendiente')
    render(:layout => "layouts/veterinarios")
  end

  def mostrarTodos
    @turnos = Turno.all.order(:estado, :dia)
    if params[:filter].present?
      @turnos = @turnos.where(estado: params[:filter])
    end
    render(:layout => "layouts/veterinarios")
  end

  def new
    @turno = Turno.new
    render(:layout => "layouts/clientes")
  end

  def create
    @turno = Turno.new(turno_params)
    @turno.estado ||= "pendiente"

    if @turno.save
      UserMailer.turno_pend(User.new(email: @turno.perro_id), @turno.tipo_turno_id, @turno.perro_id, @turno.dia).deliver
      redirect_to homeClientes_path, notice: 'Turno solicitado correctamente.'
    else
      render :new, layout: "layouts/clientes"
    end
  end

  def get_perros_by_persona
    persona_id = params[:persona_id]
    persona = Persona.find(persona_id)
    perros = persona.perros

    render json: perros
  end

  def newUrgencia
    @turno = Turno.new
    @users_activos = User.where(is_active: true, role: 0)
    @personas = @users_activos.map(&:persona)
    # render(:layout => "layouts/veterinarios")
  end

  def createUrgencia
    @turno = Turno.new(turno_params)
    @turno.estado ||= "presente"
    @turno.tipo_turno_id = TipoTurno.find_by(nombre: 'Urgencia').id
    if @turno.save
      # UserMailer.turno_pend(User.new(email: @turno.perro_id), @turno.tipo_turno_id, @turno.perro_id, @turno.dia).deliver
      # redirect_to root_path, notice: 'Turno de Urgencia creado.'
      render :presente_default, layout: "layouts/veterinarios"
    else
      render :newUrgencia, layout: "layouts/veterinarios"
      # puts "Errors: #{@turno.errors.full_messages}"
    end
  end

  def turnos_del_dia
    @turnos = Turno.where(dia: Date.today, estado: 1)
    render 'turnos_del_dia', layout: "layouts/veterinarios"
  end

  def aceptar
    @turno = Turno.find(params[:id])
  end

  def procesar_aceptar
    @turno = Turno.find(params[:id])
    hora_cita = "#{params['hora_cita(4i)']}:#{params['hora_cita(5i)']}"
    puts "Hora(4i) convertida a entero: #{params['hora_cita(4i)'].to_i}"
    if @turno.franja_horaria == 'pm' && (params['hora_cita(4i)'].to_i > 21 || params['hora_cita(4i)'].to_i < 15 )
      flash.now[:alert] = 'El cliente seleccionó franja horaria PM (entre las 15:00 y las 22:00), seleccione una hora válida o rechace el turno.'
      render :aceptar, layout: "layouts/veterinarios"
      return
    elsif @turno.franja_horaria == 'am' && (params['hora_cita(4i)'].to_i < 8 || params['hora_cita(4i)'].to_i > 11)
      flash.now[:alert] = 'El cliente seleccionó franja horaria AM (entre las 08:00 y las 12:00), seleccione una hora válida o rechace el turno.'
      render :aceptar, layout: "layouts/veterinarios"
      return
    end
    @turno.update(estado: 'aceptado')
    # @turno.update(hora: params[:hora_cita])
    hora = "#{params['hora_cita(4i)'].to_i}:#{params['hora_cita(5i)'].to_i}"
    @turno.update(hora: Time.parse(hora))
    anotacion = params[:anotacion]
    hora_cita = "#{params['hora_cita(4i)']}:#{params['hora_cita(5i)']}"
    UserMailer.turno_aceptado(User.new(email: @turno.perro.persona.user.email), @turno.tipo_turno_id, @turno.perro_id, @turno.dia, @turno.franja_horaria, anotacion, hora_cita).deliver

    redirect_to "/turnos", notice: 'Turno aceptado y correo electrónico enviado.'
  end

  def rechazar
    @turno = Turno.find(params[:id])
  end

  def procesar_rechazar
    @turno = Turno.find(params[:id])
    @turno.update(estado: 'rechazado')
    anotacion = params[:anotacion]
    UserMailer.turno_rechazado(User.new(email: @turno.perro.persona.user.email), @turno.tipo_turno_id, @turno.perro_id, @turno.dia, @turno.franja_horaria, anotacion).deliver

    redirect_to "/turnos", notice: 'Turno rechazado y correo electrónico enviado.'
  end

  def ausente
    @turno = Turno.find(params[:id])
    @turno.update(estado: :ausente)
    redirect_to "/turnos_del_dia", notice: 'Turno marcado como ausente'
  end


  def presente
    @turno = Turno.find(params[:id])
    @turno.update(estado: :presente)
    @tipo_turno = @turno.tipo_turno

    case @tipo_turno.nombre
    when 'Desparasitacion'
      render 'presente_desparasitacion', layout: 'veterinarios'
    when 'Vacuna tipo A'
      render 'presente_vacunacion', layout: 'veterinarios'
    when 'Vacuna tipo B'
      render 'presente_vacunacion', layout: 'veterinarios'
    else
      render 'presente_default', layout: 'veterinarios'
    end
  end

  def show_turno_historiaClinica
    @turno = Turno.find(params[:id])
    render(:layout => "layouts/veterinarios")
  end

  def show_turno_libretaSanitaria
    @turno = Turno.find(params[:id])
    render(:layout => "layouts/veterinarios")
  end

  def update
    @turno = Turno.find(params[:id])

    @perro = Perro.find(@turno.perro_id)
    if @turno.tipo_turno.nombre == 'Vacuna tipo A' && @perro.edad >= 2 && @perro.edad < 4
      fecha_turno_especial = Date.today + 21.days
      UserMailer.turno_vacunaa(User.new(email: @turno.perro_id), @turno.tipo_turno_id, @turno.perro_id, fecha_turno_especial).deliver
      @turno_nuevo = Turno.create
      @turno_nuevo.dia = fecha_turno_especial
      @turno_nuevo.franja_horaria = @turno.franja_horaria
      @turno_nuevo.estado = 1
      @turno_nuevo.perro_id = @turno.perro_id
      @turno_nuevo.tipo_turno_id = 1
      @turno_nuevo.save
    elsif (@turno.tipo_turno.nombre == 'Vacuna tipo A' && @perro.edad >= 4) || (@turno.tipo_turno.nombre == 'Vacuna tipo B' && @perro.edad >= 4)
      fecha_turno_especial = Date.today + 365.days
      hora_turno_especial = @turno.hora
      franja_horaria= @turno.franja_horaria
      UserMailer.turno_vacuna_anual(User.new(email: @turno.perro_id), @turno.tipo_turno_id, @turno.perro_id, fecha_turno_especial, hora_turno_especial,franja_horaria).deliver
      @turno_nuevo = Turno.create
      @turno_nuevo.dia = fecha_turno_especial
      @turno_nuevo.franja_horaria = @turno.franja_horaria
      @turno_nuevo.hora = @turno.hora
      @turno_nuevo.estado = 1
      @turno_nuevo.perro_id = @turno.perro_id
      @turno_nuevo.tipo_turno_id = @turno.tipo_turno_id
      @turno_nuevo.save
    end

    if @turno.update(turno_params)
      if @turno.perro.persona.donante
      @turno.update(monto: @turno.monto * 0.8)
      @turno.perro.persona.update(donante: false)
    end
      # Handle successful update
      if @turno.tipo_turno.nombre == "Desparasitacion"
        redirect_to show_turno_libreta_path(@turno), notice: 'Libreta Sanitaria actualizada.'
      else
        redirect_to show_turno_historia_path(@turno), notice: 'Historia Clínica actualizada.'
      end
    else
      # Handle validation errors or other issues
      render :edit
    end

  end


  def historial_gastos
    @cliente = User.find(params[:user_id])
    @turnos = Turno.where(perro_id: @cliente.persona.perros.pluck(:id)).where(estado: [:presente])
  end

  private
  def turno_params
    params.require(:turno).permit(:dia, :franja_horaria, :estado, :monto, :perro_id, :tipo_turno_id, :dosis, :descripcion, :peso)
  end

end

app/views/turnos/mostrarTodos.html.erb
<!--
  Esto es la vista de todos los turnos del veterinario
  se accede por el sidebar de la vista del veterinario
-->

<% content_for :titulo do %>
  <br>
  <div style="display: flex; align-items: center; margin-top:40px;" >
    <i class="material-icons small left grey" style="margin-right: 10px;">today</i>
    <h2 style="margin-top: 4px; font-weight: 200;"> Todos los turnos </h2>
  </div>
<% end %> 

<% content_for :titulo_acciones do %>
  <a class="btn btn-primary anchor-new-celeste" href="/turnos/subirUrgencia" style="background-color: rgb(28, 150, 174);border: none; border-radius:2px; width:100%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; margin-top:23%; justify-content: center">
    Turno de Urgencia
    <i class="material-icons" style="margin-left:15px;">add</i>
    <i class="material-icons" style="margin-left:15px;">today</i>
  </a>
  <br>
<% end %>

<% content_for :body do %>
  <div class="row mb-10">
    <div class="col-md-12">
      <%= form_tag(turnos_todos_path, method: 'get', class: 'form-inline') do %>
        <div class="row">
          <div class="col-md-4">
            <%= select_tag :filter, options_for_select(Turno.estados.keys.map { |k| [k.humanize, k] }, params[:filter]), class: 'form-control',  include_blank: "Seleccione Estado" %>
            <%# <%= select_tag :filter, options_for_select(Paseador.service_types.keys.map { |k| [k.humanize, k] }, params[:filter]), class: "form-control", include_blank: "Seleccione Tipo de Servicio" %> 
          </div>
          <div class="col-md-2">
            <button type="submit" class="btn btn-primary" style="background-color: rgb(28, 150, 174); border: none; border-radius:2px; width:100%; letter-spacing:.5px; vertical-align:center; display: flex; align-items: center; justify-content: center;">
              <i class="material-icons" style="margin-right: 5px;">search</i>
              Buscar
            </button>
          </div>
          <div class="col-md-2">
            <a class="btn btn-primary btn-volver" href="/turnosAll" style="margin-top:0%; background-color: rgb(252, 145, 14); border: none; border-radius:2px; width:100%; letter-spacing:.5px; vertical-align:center; display: flex; align-items: center; justify-content: center;">
              <i class="material-icons" style="margin-right: 5px;">close</i>
              Limpiar
            </a> 
          </div>
        </div>
      <% end %>
    </div>

  <% if @turnos.any? %>
  <%# <% if @turnos.select { |turno| turno.estado.downcase == 'pendiente' }.any? %> 
    <div class="card" style="border-radius:0; margin-top:4%;">
      <div class="card-content">
        <table class="table" style="display: table; border-collapse: separate; border-spacing: 0; position: relative; width:100%;">
          <thead>
            <tr>
              <th scope="col">Día</th>
              <th scope="col">Hora</th>
              <th scope="col">Estado</th>
              <th scope="col">Monto</th>
              <th scope="col">Perro</th>
              <th scope="col">Dueño</th>
              <th scope="col">Tipo de Turno</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @turnos.each_with_index do |turno, index| %>
              <tr>
                <% if turno.estado == 'presente' %>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= turno.dia.strftime("%d/%m/%Y") %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= turno.franja_horaria.capitalize%></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= turno.estado.capitalize %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"> 
                    <%= turno.monto %>
                  </td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= turno.perro.nombre %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= "#{turno.perro.persona.nombre} #{turno.perro.persona.apellido}" %></td>
                  <td style="background-color: rgba(200, 247, 197);, 1"><%= turno.tipo_turno.nombre %></td>
                  <td style="color:darkgreen; background-color: rgba(200, 247, 197);, 1">
                    Finalizado
                  </td>
                <% elsif turno.estado == 'cancelado' || turno.estado == 'rechazado' || turno.estado == 'ausente' %>
                  <td style="background-color: #ffecb3"><%= turno.dia.strftime("%d/%m/%Y") %></td>
                  <td style="background-color: #ffecb3"><%= turno.franja_horaria.capitalize%></td>
                  <td style="background-color: #ffecb3"><%= turno.estado.capitalize %></td>
                  <td style="background-color: #ffecb3"> 
                    -
                  </td>
                  <td style="background-color: #ffecb3"><%= turno.perro.nombre %></td>
                  <td style="background-color: #ffecb3"><%= "#{turno.perro.persona.nombre} #{turno.perro.persona.apellido}" %></td>
                  <td style="background-color: #ffecb3"><%= turno.tipo_turno.nombre %></td>
                  <td style="color:#ff6f00; background-color: #ffecb3">
                    <% if turno.estado == 'presente' %>
                      Finalizado
                    <% else %>
                      <%= turno.estado.capitalize %>
                    <% end %>
                  </td>
                <% else %>
                  <td><%= turno.dia.strftime("%d/%m/%Y") %></td>
                  <td>
                    <% if turno.hora.present? %>
                      <%= turno.hora.strftime("%H:%M") %>
                    <% else %>
                      <%= turno.franja_horaria %>
                    <% end %>
                  </td>
                  <td><%= turno.estado.capitalize %></td>
                  <td> 
                    -
                  </td>
                  <td><%= turno.perro.nombre %></td>
                  <td><%= "#{turno.perro.persona.nombre} #{turno.perro.persona.apellido}" %></td>
                  <td><%= turno.tipo_turno.nombre %></td>
                  <td>
                      <% if turno.estado == 'pendiente' && (turno.dia > Date.today) %>
                        <%= link_to 'Aceptar', aceptar_turno_path(turno.id), class: 'btn btn-success' %>
                        <%= link_to 'Rechazar', rechazar_turno_path(turno.id) , class: 'btn btn-danger' %>
                      <% elsif turno.estado == 'aceptado' && (turno.dia <= Date.today) %>
                         <% if turno.hora.present? %>
                          <% if (Time.now.hour * 3600 + Time.now.min * 60) > (turno.hora.hour * 3600 + turno.hora.min * 60) %>
                            <%= link_to presente_turno_path(turno) do %>
                              <i class="material-icons" style="color:green; margin-right:6%;" data-bs-toggle="tooltip" data-bs-placement="top" title="Asistió al turno">check</i>
                            <% end %>
                            <%= link_to ausente_turno_path(turno) do %>
                              <i class="material-icons" style="color:red" data-bs-toggle="tooltip" data-bs-placement="top" title="No asistió al turno">close</i>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% else %>
    <div class="container">
      <div class="row">
        <div class="col-md-10">
          <div class="card" style="border-radius: 0; position: relative; min-height: 100px;">
            <div class="card-content" style="position: relative; margin-bottom: 0;">
              <h4 class="mt-3">No hay turnos correspondientes </h4>
              <img src="<%= asset_path('perritoSaludando.png') %>" alt="Imagen" style="position: absolute; top: -36px; right: 20px; max-width: 23%; height: auto;">
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <br>
  <a class="btn btn-primary btn-volver" href="/homeVeterinario"
    style="background-color: rgb(28, 150, 174);border: none; border-radius:2px; width:10%; letter-spacing:.5px; vertical-align:center;display: flex; align-items: center; justify-content: center">
    Volver
    <i class="material-icons" style="margin-left:15px;">undo</i>
  </a>

<script>
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    });
  </script>
<% end %>

app/views/turnos/presente.html.erb
<% content_for :titulo do %>
  <br>
  <div style="display: flex; align-items: center; margin-top: 40px; margin-left: 50px;">
    <i class="material-icons small left grey" style="margin-right: 10px;">today</i>
    <h2 style="margin-top: 4px; font-weight: 200; margin-right: 10px;">Subir un turno de Urgencia</h2>  
  </div>
<% end %>

<% content_for :body do %>

  <h1> Turno Presente </h1>

<% end %>